name: Find and use latest tag

on:
  push:
    branches:
      - main

jobs:
  find-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0 # fetch all history, including tags

      - name: Find latest tag
        id: find-latest-tag
        run: echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
    outputs:
      tag_version: ${{ env.TAG }}

  use-tag:
    needs: find-tag
    runs-on: ubuntu-latest
    steps:
      - name: Use latest tag
        run: echo "Latest tag is ${{ needs.find-tag.outputs.tag_version }}"
