# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: deploy-on-tag

concurrency: deploying
on:
    push:
        tags:
            - "release"
    workflow_dispatch:

env:
    BRANCH_NAME: main

jobs:
    find-tag:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  ref: ${{ env.BRANCH_NAME }} # replace with the branch you want to checkout
                  fetch-depth: 0 # fetch all history, including tags

            - name: Get last git tag
              id: last_tag
              run: |
                  tagVersion=0
                  # check if git tag result is not empty string
                  if [ -n "$(git tag --list "release" --merged ${{ env.BRANCH_NAME }})" ]; then
                    echo "release exists on ${{ env.BRANCH_NAME }}"
                    LAST_RELEASE_COMMIT_ID=$(git rev-list -n 1 release)
                    echo "LAST_RELEASE_COMMIT_ID is $LAST_RELEASE_COMMIT_ID"
                    tagVersion=$(git tag --list "v[0-9]*.[0-9]*.[0-9]*" --points-at $LAST_RELEASE_COMMIT_ID | tr ' ' '\n' | sort -rV | head -n1)
                  fi
                  echo "$tagVersion"
                  echo "tagVersion=${tagVersion//v/}" >> $GITHUB_ENV
        outputs:
            tagVersion: ${{ env.tagVersion }}
    use-tag:
        needs: find-tag
        if: ${{ needs.find-tag.outputs.tagVersion }} != 0
        runs-on: ubuntu-latest
        steps:
            - name: Use last git tag
              run: |
                  image_version=${{ needs.find-tag.outputs.tagVersion }}
                  echo "commit the tag:$image_version to  feat-evironments"
