# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: deploy-on-merge

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - '*'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    types:
      - closed
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  deploy-release:
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main # replace with the branch you want to checkout
          fetch-depth: 0 # fetch all history, including tags
        
      - name: Get last git tag
        id: last_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -z "$(git tag)" ]; then
            echo "tag=0.0.0" >> $GITHUB_ENV
          else
            tag=$(git describe --tags $(git rev-list --tags --max-count=1))
            echo "tag=${tag//v/}" >> $GITHUB_ENV
          fi
      - name: Use last git tag
        run: echo "Last tag was ${{ env.tag }}"
