# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: deploy-on-merge

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - '*'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  # pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - 'main'
  # workflow_dispatch:

jobs:
  find-tag:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main # replace with the branch you want to checkout
          fetch-depth: 0 # fetch all history, including tags
        
      - name: Get last git tag
        id: last_tag
        run: |
          if [ -z "$(git tag)" ]; then
            echo "tag=0" >> $GITHUB_ENV
          else
            # tag=$(git describe --tags $(git rev-list --tags --max-count=1))
            tag=$(git describe --abbrev=0)
            # substring first 'v' character from tag, v0.0.1 => 0.0.1
            echo "tag=${tag//v/}" >> $GITHUB_ENV
          fi
      
  use-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Use last git tag
        run: |
          correctVersionRegex=^[0-9]+\.[0-9]+\.[0-9]+$ 
          commitAheadRegex=^[0-9]+\.[0-9]+\.[0-9]+-[0-9]+-[[:alnum:]]+$
          if [[ "$tag" =~ $commitAheadRegex ]]; then
              echo "Tag: $tag, does not point to the latest commit."
          else 
              if [[ "$tag" =~ $correctVersionRegex ]]; then
                  echo "commit the tag: to ${BASH_REMATCH} feat-evironments"
              else
                  echo "Last tag was return"
              fi
          fi
