# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: deploy-on-merge

on:
  # push:
  #   paths-ignore:
  #     - '**.md'
  #   branches:
  #     - '*'
  #   tags:
  #     - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    types:
      - closed
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  deploy-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged