# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: deploy-on-merge

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - '*'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  # pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - 'main'
  # workflow_dispatch:

jobs:
  find-tag:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main # replace with the branch you want to checkout
          fetch-depth: 0 # fetch all history, including tags
        
      - name: Get last git tag
        id: last_tag
        run: |
          tag=tag_not_correct
          # check if git tag result is not empty string
          if [ -n "$(git tag)" ]; then
            
            # tag = v0.0.1 kur tag eshte ne komitin e fundit ose v0.0.1-5-g34h34j kur kemi komite te tjera siper tagut
            tag=${(git describe --tags)//v/}
            correctVersionRegex=^v[0-9]+\.[0-9]+\.[0-9]+$ 
            commitsAheadRegex=^v[0-9]+\.[0-9]+\.[0-9]+-[0-9]+-[[:alnum:]]+$
            if [[ "$tag" =~ $commitsAheadRegex ]]; then
              echo "Tag: $tag, does not point to the latest commit."
              tag=tag_not_correct
            else 
              if [[ "$tag" =~ $correctVersionRegex ]]; then
                # substring first 'v' character from tag, v0.0.1 => 0.0.1
                tag=${tag//v/} 
                echo "commit the tag: to ${BASH_REMATCH} feat-evironments"
              else
                echo "tag version $tag is not in correct format"
                tag=tag_not_correct
              fi
            fi
            echo "tag found: $tag"
            echo "tag=$tag" >> $GITHUB_ENV
          fi
    outputs:
      tag_version: ${{ env.tag }}
      
  use-tag:
    needs: find-tag
    if: ${{ needs.find-tag.outputs.tag_version }} != 'tag_not_correct'
    runs-on: ubuntu-latest
    steps: 
      - name: Use last git tag
        run: |
          image_versoin=${{ needs.find-tag.outputs.tag_version }}
          echo "commit the tag: to $image_versoin feat-evironments"
