name: Pre-release Tagging Workflow

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  prerelease_tagging:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          ssh-key: ${{ secrets.TEST_GITOPS_UPDATE }}
          fetch-depth: 0 # fetch all history, including tags

      - name: Determine next pre-release index
        id: next_prerelease
        run: |
          prereleaseIndex=$(git tag --sort=-version:refname | grep -E '^pre-release.([0-9]+)' | head -n1 | awk -F'.' '{print $2+1}')
          if [ -z $prereleaseIndex]; then
            prereleaseIndex=1
          fi
          echo "NEXT_PRERELEASE_INDEX=$prereleaseIndex" >> $GITHUB_ENV
      - name: Add pre-release tag
        run: |
          prereleaseTag=pre-release.${{ env.NEXT_PRERELEASE_INDEX }}
          git config --global user.email "bardhylbegolli@gmail.com"
          git config --global user.name "BardhylGit"
          git tag -a $prereleaseTag -m "Pre-release number ${{ env.NEXT_PRERELEASE_INDEX }}"
          git push origin $prereleaseTag 
          git tag -d release
          git tag release HEAD
          git push origin --tags
