name: Pre-release Tagging Workflow

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  prerelease_tagging:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Determine next pre-release index
        id: next_prerelease
        run: echo "::set-output name=next_prerelease_index::$(git tag --sort=-version:refname | grep -E '^pre-release.([0-9]+)' | head -n1 | awk -F'.' '{print $2+1}')"
      - name: Add pre-release tag
        env:
          NEXT_PRERELEASE_INDEX: ${{ steps.next_prerelease.outputs.next_prerelease_index }}
        run: |
          prereleaseTag=pre-release.${{ env.NEXT_PRERELEASE_INDEX }}
          git tag -a $prereleaseTag -m "Pre-release number ${{ env.NEXT_PRERELEASE_INDEX }}"
          git push origin $prereleaseTag 
          git tag -d release
          git tag release HEAD
          git push origin --tags
